// <auto-generated />
namespace BookStoreDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BookListOr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookListOr));
        
        string IMigrationMetadata.Id
        {
            get { return "201506241718258_BookListOr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
